export const hospitalConstants = {

    LOGOUT: 'USERS_LOGOUT',

    GETALL_REQUEST: 'HOSPITAL_GETALL_REQUEST',
    GETALL_SUCCESS: 'HOSPITAL_GETALL_SUCCESS',
    GETALL_FAILURE: 'HOSPITAL_GETALL_FAILURE',
};
